version: "3.1"
services:
  postgres:
    container_name: pg_container
    image: postgres:14.1
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "attractiondb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "A@rtzu123"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"
  app:
    image: 'attraction-app.jar'
    container_name: attraction
    command: ./attraction-app.jar
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/attractiondb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=A@rtzu123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "A@rtzu123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
networks:
  postgres:
     driver: bridge