version: "3.9"
services:
  postgres:
    container_name: pg_container
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: "attractiondb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "A@rtzu123"
    ports:
      - "54321:5432"