---------------------
1)Создать основы Spring Boot сервиса, зависимости:
(Lombok, Spring Web, Spring Data Jpa, JUnit Jupiter API)

2)Cоздание объектов предметной области

3)Создать бд с использованием скриптов Liquibase

4)Создать репозиторий (возможно не для всех сущностей понадобяться репозитории)
 .Создать кастомные методы

5)Создать сервисы и реализовать методы репозитория, написать бизнес логику
 .Сделать JUnit тесты методов

6)Проектирование и документирование REST API сервиса

6)Создать несколько контроллеров которые будут иметь следующие методы:
//Принимаем в запросе широту и долготу
1)Получать список достопримечательностей в указанном радиусе(широта, долгота): 
   //Возможность выбирать по чему фильтровать(либо категория, либо оценка) и возможность фиьтровать по двум параметрам (принимаем категорию и оценку в теле)
  .Возможность фильтрации по категории и оценке
   //Если отправляеться без определнного кол-ва то будет показан defolt, если отправиться с опреденным числом то будет выданно это кол-во достпр.
  .Кол-во достопримечательностей(дефолт - 10) которые сортируются по близости 
  // Указывать город в запросе и получать все достопремечательности в теле Json)
2)Получить все достоп. в указанном городе(getAll - где указан город), фильтрация и сортировка как в 1 пункте 
//Отравляем название достопремечательности и отзыв с оценкой в теле Json
3)Возможность поставить оценку и отзыв конкретной достопримечательности (Их связь смотреть в схеме, 2 ее взможных варианта) 
4)Возможность получить информацию по конкретной достопримечательности ее оценку и отзывы




